@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Jun 18 18:03:36 +0800 2018
REM SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
call xelab  -wto b195aa44af494d82a9803956b2de6129 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L blk_mem_gen_v8_3_6 -L axi_bram_ctrl_v4_0_14 -L blk_mem_gen_v8_4_1 -L lib_pkg_v1_0_2 -L fifo_generator_v13_2_2 -L lib_fifo_v1_0_11 -L lib_srl_fifo_v1_0_2 -L lib_cdc_v1_0_2 -L axi_datamover_v5_1_18 -L axi_sg_v4_1_9 -L axi_dma_v7_1_17 -L proc_sys_reset_v5_0_12 -L generic_baseblocks_v2_1_0 -L axi_data_fifo_v2_1_15 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_16 -L axi_protocol_converter_v2_1_16 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot sim_k7_cyslff_behav xil_defaultlib.sim_k7_cyslff xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
